name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
      
      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace CounterApp.xcworkspace -scheme CounterApp -configuration Release -sdk iphoneos -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Create Payload directory
        run: |
          cd ios/build/Build/Products/Release-iphoneos
          mkdir Payload
          cp -r CounterApp.app Payload

      - name: Create IPA
        run: |
          cd ios/build/Build/Products/Release-iphoneos
          zip -r CounterApp.ipa Payload

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: CounterApp-ios
          path: ios/build/Build/Products/Release-iphoneos/CounterApp.ipa

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1
          release_name: Release v0.1
          draft: false
          prerelease: false

      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ios/build/Build/Products/Release-iphoneos/CounterApp.ipa
          asset_name: CounterApp.ipa
          asset_content_type: application/octet-stream
